### ISSUE TITLE
请指导

### ISSUE THREAD

**Issue by LinWeiLiang-hub** [haoruilee/ZuiSuWaiMai#1]
你好，我想请问一下，我打开debug中的.exe文件  显示缺少dll(url)

**Comment by haoruilee** [comment]
方便留下邮箱吗？我已经离开这个项目很久了，可以把原工程文件发给你。Github存在上传大小限制因此可能有些文件缺失

发件人: LinWeiLiang-hub
发送时间: 2020年8月27日 15:55
收件人: haoruilee/ZuiSuWaiMai-MFC
抄送: Subscribed
主题: [haoruilee/ZuiSuWaiMai-MFC] 请指导 (#1)

你好，我想请问一下，我打开debug中的.exe文件 显示缺少dll(url)

**Comment by LinWeiLiang-hub** [comment]
你好，谢谢。邮箱是1336364643@qq.com。太感谢了

**Comment by LinWeiLiang-hub** [comment]
你好，我留给您一个QQ邮箱。1336364643@qq.com。谢谢！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "haoruilee/ZuiSuWaiMai-MFC"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月27日(星期四) 下午5:56
收件人:&nbsp;"haoruilee/ZuiSuWaiMai-MFC"<ZuiSuWaiMai-MFC@noreply.github.com&gt;;
抄送:&nbsp;"Willian 壹"<1336364643@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [haoruilee/ZuiSuWaiMai-MFC] 请指导 (#1)





 
 方便留下邮箱吗？我已经离开这个项目很久了，可以把原工程文件发给你。Github存在上传大小限制因此可能有些文件缺失 
 
 发件人: LinWeiLiang-hub 
 发送时间: 2020年8月27日 15:55 
 收件人: haoruilee/ZuiSuWaiMai-MFC 
 抄送: Subscribed 
 主题: [haoruilee/ZuiSuWaiMai-MFC] 请指导 (#1) 
 
 你好，我想请问一下，我打开debug中的.exe文件 显示缺少dll(url)

**Comment by haoruilee** [comment]
添加了原始项目代码的网盘链接至Readme
